import Head from "next/head"
import Navbar from '../components/Navbar'

export default function Layout({ children }) {
    return (<>
        <Head>
            <title>Immortal Garments</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css" integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==" crossOrigin="" />
        </Head>
        <header>
            <h1>Immortal Garments</h1>
            <Navbar />
        </header>
        <main>
            {children}
        </main>
    </>);
}